version: "1.0"
services:
  trainer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/src
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    shm_size: '8gb'
